Adding responsive navbar feature and rescaling the main content
KSU-Google-DSC/Webapp pull request #24
Opened 2022-07-24 20:34 UTC by aimiisme

Creating a responsive design for the navigation bar and scaling the main content of the landing page.

2022-07-25 06:37 UTC, Sanjay-B commented
Hi Aimi, I will look at this in a bit.

2022-07-25 07:02 UTC, Sanjay-B requested changes
Formatting a changes and some changes need to be made. Overall though, really good.

2022-07-25 07:02 UTC, Sanjay-B commented on src/pages/index.js
> +        <img src='/static/images/dsc-word.PNG' style={{height:"auto", width:"100%"}}/>
Not a fan of using the image since the quality looks really bad compared to the rest of the site. We want consistency in quality. I think this would be better served as html tags than as a standalone image. i.e All the elements in the image should be just html tags and the image should be removed.

2022-07-25 07:33 UTC, Sanjay-B commented on src/components/navbar.js
> +                                <Tab  key={index} label={page}></Tab>
Each tab is missing an `href` that would send them to that page's url. Right now, if you were to click the button, it does nothing.

2022-07-25 07:34 UTC, Sanjay-B commented on src/components/DrawerComp.js
> +                        <ListItemButton onClick={()=> setOpenDrawer(false)} key={index}>
Each button is missing an `href` that would send them to that page's url. Right now, if you were to click the button, it does nothing. Not sure if this is done on purpose or by mistake. Please let me know.

2022-07-31 03:29 UTC, aimiisme commented
I have replaced the `<img>` tag with `<html>` tags and re-formatting the code. The landing page is now responsive. I'm currently trying to fix some bugs on the navbar to link the button to other page's URL. It's going to be committed under different branch.

2022-08-01 03:56 UTC, Sanjay-B approved these changes
Amazing work! Approved. (Landing Page & Navbar)

2022-08-01 04:06 UTC, Sanjay-B requested changes
Good start but, this is should all be in a separate pull request specifically for the `About Page`.

2022-08-01 04:06 UTC, Sanjay-B commented on src/pages/about.js
> +import React from "react";
Incomplete. This should be in its own pull request.

2022-08-01 04:06 UTC, Sanjay-B commented on src/pages/about.js
> +          <Typography variant="body1" color="text.secondary">
Why are you using multiple `<Typography variant="body1">` tags? You could just use one.

2022-08-01 04:06 UTC, Sanjay-B commented on src/pages/about.js
> +        <CardMedia
This is a placeholder image, correct?

2022-08-01 04:06 UTC, Sanjay-B commented on src/components/navbar.js
> +                {PAGES.map((page, index) => (
You need `href` so that you can point each button / tab to the page url.  i.e User clicks `About` tab and automatically goes to the `About` page.

2022-08-01 13:51 UTC, aimiisme commented
> Good start but, this is should all be in a separate pull request specifically for the `About Page`. 

It was a mistake. This pull request is for the navbar only. The href tag will be updated soon.

2022-08-02 14:48 UTC, aimiisme commented on src/pages/about.js
> +        <CardMedia
Yes.

2022-08-02 14:49 UTC, aimiisme commented on src/components/navbar.js
> +                {PAGES.map((page, index) => (
David and me are working on it since we have some bugs while trying to link tabs with router.

2022-08-08 03:31 UTC, Sanjay-B commented on src/components/navbar.js
> +                {PAGES.map((page, index) => (
Sounds good. That definitely needs to work. If you need help, let me know.

2022-08-08 03:32 UTC, Sanjay-B commented
Request another review when changes have been made. @aimiisme

2022-08-17 05:27 UTC, Sanjay-B commented on src/components/navbar.js
> +                {PAGES.map((page, index) => (
Addressed in: https://github.com/KSU-Google-DSC/Webapp/pull/24/commits/aa6af228704809ae3d3247ec4bfb3cd141a8d6ea

2022-08-18 00:07 UTC, Sanjay-B requested changes

2022-08-18 00:07 UTC, Sanjay-B commented on src/pages/index.js
> +import { Box, Grid, Typography, Stack, Button } from "@mui/material";
![Screenshot 2022-08-17 200132](https://user-images.githubusercontent.com/22083307/185264227-a5412543-3bb2-4f1d-ba42-9c80cc0093dc.png)

Not sure why this is happening but, definitely needs to be fixed. White space is bad in this scenario.

2022-08-18 02:43 UTC, aimiisme commented on src/pages/index.js
> +import { Box, Grid, Typography, Stack, Button } from "@mui/material";
Please ignore that change in the `feature/responsive_landing_page` branch. This issue has been fixed in the different branch called `feature/wave_animation`, the wave is animating as well.

2022-08-18 05:24 UTC, Sanjay-B commented on src/pages/index.js
> +import { Box, Grid, Typography, Stack, Button } from "@mui/material";
Alright, that's fine. Thanks for letting me know. @aimiisme

2022-08-24 00:10 UTC, Sanjay-B approved these changes
LGTM - Looks good to me.

2022-08-24 00:11 UTC, merged