Add event endpoint
KSU-Google-DSC/Webapp pull request #28
Opened 2022-08-12 23:24 UTC by KaitlynOlinger

2022-08-12 23:25 UTC, theTechOwl approved these changes

2022-08-13 04:39 UTC, Sanjay-B commented
Hi Kaitlyn, I will review this later today. Don't worry about the "failed deployment" warnings shown here.

2022-08-13 10:55 UTC, theTechOwl commented
Dear Sanjay,

Thank you very much. Please note that I also reviewed her code and approved the request. However, it requires 1 more person to approve the code before the pull request can be accepted.


Sincerely,
David Chavarro
________________________________
From: Sanjay ***@***.***>
Sent: Saturday, August 13, 2022 12:39:57 AM
To: KSU-Google-DSC/Webapp ***@***.***>
Cc: David Chavarro ***@***.***>; Comment ***@***.***>
Subject: Re: [KSU-Google-DSC/Webapp] Implement Event Endpoints (/events) (PR #28)


Hi Kaitlyn, I will review this later today. Don't worry about the "failed deployment" warnings shown here.

—
Reply to this email directly, view it on GitHub<https://github.com/KSU-Google-DSC/Webapp/pull/28#issuecomment-1213664945>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AN5Q7W7DJISNM4TWSFMMBB3VY4RJ3ANCNFSM56ND6OTA>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-08-13 23:16 UTC, Sanjay-B requested changes
Decent but, needs work. 

Some of these can be dynamic api routes if you're storing events based on an id. https://nextjs.org/docs/api-routes/dynamic-api-routes

2022-08-13 23:16 UTC, Sanjay-B commented on src/pages/api/database-deployment.js
> +const serviceAccount = require('MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC7SCA0A6mpDHpC\nzvSSvvQCwV5hTI4EtVFldzcmtG+/Ciyzm3/WkybJzI/U0zx9tBr1dmKJhL14W+Tt\n3qcSdgmOmo45mKn1dZVJ98JsUFKpa7wVtCn
This is extremely bad. Do not leak a token that can be used on a database. Since this is a test token, the severity of it is less but, don't do this. Look into `environmental variables (.env)`.

2022-08-13 23:16 UTC, Sanjay-B commented on src/pages/api/database-deployment.js
> +const db = getFirestore();
Do we have multiple implementations of this? I could've sworn I've seen something like this written in one of the PRs. If so, have only one implementation.

2022-08-13 23:16 UTC, Sanjay-B commented on src/pages/api/event-add-data.js
> +//Generic data to start Events "table"
This should be a POST request. Data isn't static. It's dynamic. In this case though, it should be the request body (payload) that is inputed into the database. Neat POC (proof of concept) but, it still has to fit our use case.

2022-08-13 23:16 UTC, Sanjay-B commented on src/pages/api/event-endpoints.js
> +//app.use(express.json());
This whole file is wrong. NextJS (the framework this project uses) has api routes baked in. You don't need to use express (which is another framework) to do the same thing. Look into this: https://nextjs.org/docs/api-routes/introduction

Otherwise, the actual body of these methods seem correct. It just needs to fit NextJS.

2022-08-13 23:23 UTC, Sanjay-B commented
> Dear Sanjay, Thank you very much. Please note that I also reviewed her code and approved the request. However, it requires 1 more person to approve the code before the pull request can be accepted. Sincerely, David Chavarro

Future reference, make sure that you **properly review** code that is being pushed. Looking correct is not the same as **being correct**. Look at my review comments for inspiration.

2022-08-31 19:41 UTC, Sanjay-B commented
Update: @KaitlynOlinger followed up with me. This is still a work in progress.

2022-09-30 05:59 UTC, Sanjay-B commented on src/pages/api/event-add-data.js
> +//Generic data to start Events "table"
Stale. Resolving.

2022-09-30 05:59 UTC, Sanjay-B commented on src/pages/api/event-endpoints.js
> +//app.use(express.json());
Stale. Resolving.

2022-09-30 06:00 UTC, Sanjay-B reviewed
This is out of touch with dev by quite a large margin. Should've been kept up with. Moving this to another branch so I can balance changes correctly. cc: @PremKSU

2022-09-30 08:05 UTC, Sanjay-B commented
Closed. Moved to: https://github.com/KSU-Google-DSC/Webapp/pull/42

2022-09-30 08:05 UTC, closed without merging