Prod Nomination 1
KSU-Google-DSC/Webapp pull request #44
Opened 2022-09-30 15:54 UTC by Sanjay-B

2022-09-30 16:54 UTC, PremKSU approved these changes
Most front-end changes look good to me. Hamburger menu, get started button, and navbar home button seem to be working fine. I cannot speak on the functionality of backend right now. Can we remove the logo from the About page? Can comment it out for now, and update it when we have a better picture to put in.

2022-10-01 14:52 UTC, aimiisme approved these changes
I approve those commits for now, even though we still need to develop this project. Those are ready to be merged into the `main` branch.

2022-10-01 19:54 UTC, Sanjay-B commented
Appreciate the reviews thus far. I am going to hold off until we get deployment working. Blocked by https://github.com/KSU-Google-DSC/Webapp/pull/45 . @PremKSU cc: @aimiisme , @teamrocket77

2022-10-12 18:45 UTC, Sanjay-B commented
Where are we with this? @PremKSU

2022-10-23 20:42 UTC, Sanjay-B commented
**Blocked: ** RC0 (this PR) fails to build docker during deployment via Github Actions. I am looking into a fix. Est: ~After Tuesday (10/23/22).

2022-10-23 20:42 UTC, Sanjay-B commented
**Blocked:** RC0 (this PR) fails to build docker during deployment via Github Actions. I am looking into a fix. Est: ~After Tuesday (10/23/22). 

cc: @PremKSU

2022-10-31 03:14 UTC, Sanjay-B commented
Blocked: RC0 (this PR) fails to build docker during deployment via Github Actions. I am looking into a fix. Deployment keys are valid and are present as secrets in the repo. Est: ~idk

Still blocked by the issue. Can't seem to find a fix.

cc: @PremKSU

2022-11-07 03:21 UTC, teamrocket77 commented on .github/workflows/gcr_deployment.yml
> +  release:
Do we have any successful runs for this action? if not there is a `workflow_dispatch` option
[Manually running](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)
[workflow_dispatch event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)

2022-11-07 03:29 UTC, teamrocket77 requested changes
Just looking for some answers, lots of things have changed

2022-11-07 03:29 UTC, teamrocket77 commented on CONTRIBUTING.md
> +`SECRET` and `NEXTAUTH_SECRET` can be created by typing `openssl rand -base64 32` into the terminal.
We longer use pre generated creds @Sanjay-B ?

2022-11-07 03:29 UTC, teamrocket77 commented on Dockerfile
> +COPY /src/.env /app/src
this should take care of all the copying
why are we copying .env & package*.json files file separately? 
Given the current nature of the project does this build for you?
@Sanjay-B

2022-11-07 17:14 UTC, Sanjay-B commented on Dockerfile
> +COPY /src/.env /app/src
Dependencies step installs only dependencies. @teamrocket77

2022-11-07 17:14 UTC, Sanjay-B commented on CONTRIBUTING.md
> +`SECRET` and `NEXTAUTH_SECRET` can be created by typing `openssl rand -base64 32` into the terminal.
For dev environments, they'd still have to pre-generate this.

2022-11-07 17:31 UTC, Sanjay-B commented on .github/workflows/gcr_deployment.yml
> +  release:
Yeah, I think that option is good. I am going to add it in. @teamrocket77

2022-12-28 22:49 UTC, Sanjay-B commented
**Update**: Deployment is being looked into by @Sanjay-B , @teamrocket77 . We've narrowed it down to build keys being passed via the Docker container and failing to be recognized by the build environment when the application enters into start-mode. Looking into possible solutions. RC0 will now be shipped with Cypress (Testing Environment). We're still looking into the issue that this poses for the Events page. I will follow up in internal channels.

2022-12-31 22:38 UTC, Sanjay-B commented
Update: RC0 is no longer blocked. Produces runnable build & deployment.

2023-01-02 23:38 UTC, Sanjay-B commented
Update: Blocked by missing functionality in Submit button in ``/opportunities`` and ``/team`` not being connected to the backend. 
cc: @aimiisme , @johnnymcmike

2023-01-02 23:40 UTC, Sanjay-B commented
Pushed RC0 release to ``1/6/23`` to give time to fix said issues.

2023-01-09 05:24 UTC, Sanjay-B reviewed
LGTM. Merging into ``main``.

2023-01-09 05:25 UTC, merged