Support GCP Deployment through Docker
KSU-Google-DSC/Webapp pull request #45
Opened 2022-10-01 19:54 UTC by Sanjay-B

2022-10-01 19:56 UTC, Sanjay-B commented
Docker works and it deploys. Assets seem to be missing and production keys aren't getting registered correctly. Looking into this. cc: @PremKSU

2022-10-01 22:11 UTC, Sanjay-B commented
Should be working now. @teamrocket77 please verify & review / approve the PR.

2022-10-01 23:09 UTC, teamrocket77 commented
Used tool `hadolint` to correct docker file

2022-10-01 23:11 UTC, teamrocket77 approved these changes
LGTM!

2022-10-02 05:01 UTC, Sanjay-B commented
I requested a re-review since I added more stuff. @teamrocket77 cc: @PremKSU

2022-10-12 01:29 UTC, teamrocket77 requested changes
just feedback for the questions
@Sanjay-B

2022-10-12 01:29 UTC, teamrocket77 commented on .github/workflows/gcr_deployment.yml
> +  CLOUD_RUN_PROJECT_ID:
@Sanjay-B at any point do you intend on setting these values via the secrets option in GH

2022-10-12 01:29 UTC, teamrocket77 commented on .gitignore
> +**/.env.development
@Sanjay-B would something like `**/env.*` suffice here

2022-10-12 01:29 UTC, teamrocket77 commented on src/package.json
> +    "start": "next start -p $PORT",
How is `$PORT` going to be configured?

2022-10-12 18:58 UTC, Sanjay-B commented on .gitignore
> +**/.env.development
Yeah, that would be better. Fixed as of https://github.com/KSU-Google-DSC/Webapp/pull/45/commits/7c85e91d0e8b1bd0c5a3dc98c57350249b67d46b.

2022-10-12 18:59 UTC, Sanjay-B commented on src/package.json
> +    "start": "next start -p $PORT",
That's if we want to configure a port # with GitHub actions & secrets. i.e ``next start -p $PORT`` should be ``next start`` because, we could just do ``next start -p secrets.port`` in a docker file or GitHub action. I reverted back to what it was since ``-p`` option can be specified based on use-case rather than defaulted. Fixed as of https://github.com/KSU-Google-DSC/Webapp/pull/45/commits/7c85e91d0e8b1bd0c5a3dc98c57350249b67d46b.

2022-10-12 20:34 UTC, teamrocket77 approved these changes
Looks good

2022-10-23 19:40 UTC, teamrocket77 approved these changes

2022-10-23 19:42 UTC, Sanjay-B commented
Looks good. Merging for RC-0. cc: @PremKSU

2022-10-23 19:43 UTC, merged