Remove unauthenticated api/applicants/submit endpoint
KSU-Google-DSC/Webapp pull request #57
Opened 2022-11-02 00:36 UTC by johnnymcmike

Introduced in one of my previous PRs, the api/applicants/submit open endpoint simply pastes whatever JSON you throw at it into the database. As dev is now, it is allowing all POST requests made to this URL! Until we get authenticatd endpoints working, I have been requested to disable the unsafe endpoint. This PR does that.

2022-11-10 17:49 UTC, Sanjay-B requested changes
Overall looks good. All PRs labeled under `security` needs a security opinion / review before merging. So, I've included @teamrocket77 as a reviewer.

2022-11-10 17:49 UTC, Sanjay-B commented on src/pages/api/applicants/submit.js
> +// import { firestoreApp  } from '../../../database';
Nitpick: Would appreciate a comment explaining why this is commented out. Even though it's inherently obvious to us, it won't be for those who have no knowledge about this PR.

2022-11-10 18:34 UTC, teamrocket77 commented on src/pages/api/applicants/submit.js
> +// import { firestoreApp  } from '../../../database';
I agree I think a comment would do others some good.

2022-11-10 18:39 UTC, teamrocket77 requested changes
Requested: Comments explaining why this is commented out

2022-11-11 21:52 UTC, johnnymcmike commented on src/pages/api/applicants/submit.js
> +// import { firestoreApp  } from '../../../database';
Good point, comment added in latest commit

2022-11-12 00:13 UTC, teamrocket77 reviewed
LGTM

2022-11-12 00:14 UTC, teamrocket77 approved these changes
LGTM

2022-11-13 20:17 UTC, Sanjay-B approved these changes
Looks good to me.

2022-11-13 20:18 UTC, Sanjay-B commented
Reviewing conditions have been met. Merging into ``dev``. Thank you for correcting this. @johnnymcmike cc: @PremKSU

2022-11-13 20:18 UTC, merged