Changed spacing for upcoming events
KSU-Google-DSC/Webapp pull request #58
Opened 2022-11-09 19:23 UTC by Mike865

Changed grid component sizes so that the mobile page will not over flow and look better. Changed the weekday, date day, and date year attribute sizes to be bigger. Changed outline of date information from gray to blue. Removed icon from see details button and changed icon for the add to calendar button. Added a color in theme.js called outline for the outline color of the date box.

2022-11-10 17:44 UTC, Sanjay-B requested changes
Few feedback comments. Programmatically, this looks good. Design-wise, up to @aimiisme.

2022-11-10 17:44 UTC, Sanjay-B commented on src/components/EventCardFlip.js
Overall text might be too big. Defer to @aimiisme for design review. cc: @aimiisme @PremKSU

2022-11-10 17:44 UTC, Sanjay-B commented on src/components/EventCardFlip.js
> +                  <a href={props.locationData}>{props.locationData}</a>
Does not wrap correctly in mobile view. Refer to picture. 

<img width="562" alt="Screen Shot 2022-11-10 at 12 41 02 PM" src="https://user-images.githubusercontent.com/22083307/201168418-9d20414e-fe79-4efe-850f-9b6d8506949d.png">

cc: @PremKSU

2022-12-27 18:42 UTC, aimiisme commented on src/components/EventCardFlip.js
> +                  <a href={props.locationData}>{props.locationData}</a>
I wiil work with @Mike865 to resolve this issue soon.

2022-12-29 20:52 UTC, aimiisme commented on src/components/EventCardFlip.js
@Mike865 has reduced the text size in his latest commit and they look good to me.

2022-12-29 21:01 UTC, aimiisme reviewed
@Sanjay-B I'm experiencing some difficulty viewing the event flip card on my computer (I believe it's just not working for me.) However, I have reviewed the screenshot that Michael sent me, and the overall design looks good to me. Would you mind checking if the hyperlink works for each `location.type` that we discussed?

2022-12-31 22:39 UTC, Sanjay-B commented
> @Sanjay-B I'm experiencing some difficulty viewing the event flip card on my computer (I believe it's just not working for me.) However, I have reviewed the screenshot that Michael sent me, and the overall design looks good to me. Would you mind checking if the hyperlink works for each `location.type` that we discussed?

![image](https://user-images.githubusercontent.com/22083307/210156855-2c838220-5489-46ef-9c2d-85d82b58e82b.png)

I rebalanced this branch with ``origin/dev``. It produces the error above. Do you see the same? @aimiisme , @Mike865

2022-12-31 22:41 UTC, Sanjay-B reviewed
Refer to earlier comment. This looks good but, ``http://localhost:3000/events`` does not load for me.

2023-01-09 01:31 UTC, Sanjay-B commented
Update: Since ``/events`` is not part of RC0, I am going to defer this to RC1. @Mike865 cc: @aimiisme

2023-01-31 06:08 UTC, Sanjay-B approved these changes
LGTM.

2023-02-22 19:06 UTC, Sanjay-B commented
I am closing this because it's stale. Feel free to reopen if need be. @Mike865 cc: @aimiisme , @Hoangnguy02 , @zainabm9786

2023-02-22 19:06 UTC, closed without merging