Fixed the about page visual component.
KSU-Google-DSC/Webapp pull request #59
Opened 2022-11-10 03:17 UTC by Hoangnguy02

#53
I changed the image inside the About page, and move it to the top so it won't be too much space on the right side.   
The margin and font size are also changed depending on the screen size.

2022-11-10 17:20 UTC, Sanjay-B commented
Resolve ``.gitignore`` conflicts. @aimiisme

2022-11-10 17:26 UTC, Sanjay-B requested changes
Minor complaints. I think it mainly has to do with the directory structure. I believe, and correct me if I am wrong, the directory structure in the PR / branch is widely different than ``dev`` branch. Typically that shouldn't be the case. Outside of that, the bug fix looks good. 
cc: @aimiisme @PremKSU

2022-11-10 17:26 UTC, Sanjay-B commented on package.json
> +{
Why is ``package.json`` outside of the ``src`` folder? Also, these dependencies look different from the ``dev`` branch.

2022-11-10 17:26 UTC, Sanjay-B commented on .gitignore
> +node_modules
This is in the ``.gitignore`` already via ``src/.gitignore``. Curious as to why this is needed.

2022-11-10 17:37 UTC, aimiisme commented on package.json
> +{
I think the issue that Sanjay mentioned above happens because you forgot to `cd src` before `npm ci` to install dependencies. That is also the reason why package.json is outside of the src folder. @Hoangnguy02

2022-11-10 18:16 UTC, Sanjay-B commented on package.json
> +{
> I think the issue that Sanjay mentioned above happens because you forgot to `cd src` before `npm ci` to install dependencies. That is also the reason why package.json is outside of the src folder. @Hoangnguy02

That's probably the issue.

2022-11-12 17:40 UTC, Hoangnguy02 commented
Hi, I was kind of messing up when downloading the webApp and forgot to do cd src before npm ci. Please ignore and close this pull request. I will replace it with a new one. I'm sorry for this inconvenience. 
Here is the link: https://github.com/KSU-Google-DSC/Webapp/pull/61 
(#61)

2022-11-13 20:12 UTC, Sanjay-B commented
Closed in favor of https://github.com/KSU-Google-DSC/Webapp/pull/61. cc: @PremKSU

2022-11-13 20:12 UTC, closed without merging