Major Changes to Packages:
KSU-Google-DSC/Webapp pull request #62
Opened 2022-11-13 23:57 UTC by teamrocket77

# File Changes
Changes to files:
1. Created an github action install packages, and runs the npm scrips provided, after it runs everything it will take whatever that's in the screenshots folder and upload it
2. There is also a prepatory script that gets all of the file names from the `/pages` directory
3. Made small tag edits to the navbar material UI so the testing function will be able to find components, which is important in the case of loading

# Major Changes to packages.json and package-lock.json
1. Added wait-on npm package
1. Added the Cypress Package

Why? Cypress will be our testing suite and wait-on is what we can use to know when the node app is fully built and running for testing

[Cypress Docs](https://docs.cypress.io/guides/overview/why-cypress) 
[npm wait-on information](https://github.com/jeffbski/wait-on)

Major Commands for testing yourself:
1. `node ./cypress/prep_functions/page_fixture_creator.js` will run the fixture prep function
1. `npm run dev & wait-on http://localhost:3000` starts the dev server and we wait for our default testing port
1. `npx cypress open` this will open an editor for you to test things
1. `npx cypress run` this will run all tests components and e2e has `--e2e` `--components` and `--spec` variants

2022-11-14 00:40 UTC, teamrocket77 commented on .github/workflows/screenshot_action.yml
> +      - 'gui/**'
there was a message offline about this a while back, I don't know if you'd like to run this as the gui gets updates either way just lemme know and I can either update this to be something like '**/gui/**' or remove it completely

2022-12-28 22:42 UTC, Sanjay-B requested changes
Left some feedback & additional questions. @teamrocket77

2022-12-28 22:42 UTC, Sanjay-B commented on .github/workflows/screenshot_action.yml
> +      - 'gui/**'
Update: We had a chat about this offline. Instead of branch naming. Make this tag based. Tag should be named "UI". Ideally, once that tag is placed on a Pull Request. It kicks off this action. @teamrocket77

2022-12-28 22:42 UTC, Sanjay-B commented on src/cypress/e2e/screenshots.cy.js
> +		let webPath = 'http://localhost:3000';
Might want to look into defining this better. `http://localhost:3000` is set as default but, it's rather easy to override this. @teamrocket77

2022-12-28 22:42 UTC, Sanjay-B commented on src/cypress/fixtures/pages.json
> +{"pages":["about","opportunities","socials","team"]}
Missing Events page? @teamrocket77

2022-12-28 22:42 UTC, Sanjay-B commented on src/cypress/support/commands.js
> +// ***********************************************
Move all this to a possible docs solution that was talked about in meeting. @teamrocket77

2023-01-01 18:03 UTC, Sanjay-B commented on src/cypress/e2e/screenshots.cy.js
> +		let webPath = 'http://localhost:3000';
Update: Took this offline - Not that important. What is listed is fine.

2023-01-01 19:29 UTC, teamrocket77 commented
#Final thoughts and inputs:
- had to test with push and adding and removing the label seems like state may be cached, you can see the successful runs, in the actions tab
[With the UI/UX tag](https://github.com/KSU-Google-DSC/Webapp/actions/runs/3818334833) 
 - Note that the tests wasn't skipped and there is an artifacts folder for this test
[Without the UI/UX Tag](https://github.com/KSU-Google-DSC/Webapp/actions/runs/3818314257)
 - Note: this test was skipped

Screenshots:
<img width="1536" alt="all_tests_running" src="https://user-images.githubusercontent.com/14345179/210182544-70b56bfd-e8ff-485a-bf31-c28e595c9f4c.png">
<img width="1536" alt="ui_tag" src="https://user-images.githubusercontent.com/14345179/210182546-4a3b24e1-b501-40c9-af81-ad099279fc8e.png">
<img width="1536" alt="test_skipped" src="https://user-images.githubusercontent.com/14345179/210182548-cce6cd13-41b4-439b-b105-fc25e4612886.png">
<img width="1536" alt="no_ui_tag" src="https://user-images.githubusercontent.com/14345179/210182549-eb489fd2-488b-442b-8c79-3be58a725660.png">

2023-01-01 21:21 UTC, teamrocket77 commented
Actions can be reran [here](https://github.com/KSU-Google-DSC/Webapp/actions/runs/3818737957)
You can add and remove the UI/UX tag to get the workflow to run

2023-01-02 18:05 UTC, Sanjay-B requested changes
This looks great. Nice work! I would make ``Docs/Automation/...`` be ``docs/automation`` since everything else in the repo is lower-case. More consistent.

2023-01-02 19:53 UTC, teamrocket77 commented
Docs and Automation folder names have been changed

2023-01-02 23:31 UTC, Sanjay-B approved these changes
Great work! Approved.

2023-01-02 23:34 UTC, merged