Implemented Login Page
KSU-Google-DSC/Webapp pull request #63
Opened 2022-12-29 20:46 UTC by aimiisme

- Implemented the Login Page. The `Sign In` button is linked to the `dashboard.js` even though it has not been validated yet
- Added a new folder called `dashboard `in the `src` folder for further dashboard implementation.

2022-12-31 22:53 UTC, Sanjay-B requested changes
~~Code looks good. There's an empty ``src/dashboard/dashboard.js`` file that got pushed in. Not sure if that was intentional or by mistake. @aimiisme~~ Resolved down in comments.

2022-12-31 22:55 UTC, Sanjay-B commented on src/pages/login.js
> +                    {"Don't have an account? Sign Up"}
This not needed since the username & password will be created by a website admin.

2022-12-31 22:57 UTC, Sanjay-B requested changes

2022-12-31 22:57 UTC, Sanjay-B commented on src/pages/login.js
> +                    Forgot password?
This not needed since the password will be provided by a website admin.

2022-12-31 22:57 UTC, Sanjay-B commented on src/pages/login.js
> +              <TextField
Sanitize your inputs. This makes it easy for someone to possibly use a SQL injection to exploit and gain access to data.

2022-12-31 22:57 UTC, Sanjay-B commented on src/pages/login.js
> +              <TextField
Sanitize your inputs. This makes it easy for someone to possibly use a SQL injection to exploit and gain access to data.

2022-12-31 22:57 UTC, Sanjay-B commented on src/pages/login.js
> +export default function SignIn() {
The design from Adobe XD is different from what is implemented here. Was this intentional?

2022-12-31 22:57 UTC, Sanjay-B commented on src/pages/login.js
> +                    {"Don't have an account? Sign Up"}
This not needed since the username & password will be created by a website admin.

2023-01-01 00:17 UTC, aimiisme commented
> Code looks good. There's an empty `src/dashboard/dashboard.js` file that got pushed in. Not sure if that was intentional or by mistake. @aimiisme 
The empty `src/dashboard/dashboard.js` file was pushed in intentionally as a "starting point" for frontend people to continue to work on that. The `Sign In` button on the `Login page` is linked to the `dashboard.js`. @Sanjay-B

2023-01-01 00:36 UTC, aimiisme commented on src/pages/login.js
> +export default function SignIn() {
It was changed intentionally because I experienced some issues with the `z-index` and `overflow` errors of the wave animation for a month but still haven't figured out what happened. Also, I think this Login Page must be completed asap so my other team members will have the starting point to start implementing the `dashboard`. This current design of the login page looks good to me though. If you don't like this new version, I'll need to take more time to figure out the issues that I mentioned above. @Sanjay-B

2023-01-01 00:37 UTC, Sanjay-B commented on src/pages/login.js
> +export default function SignIn() {
I think that it's perfect. You could always touch up on it later. @aimiisme

2023-01-01 00:38 UTC, Sanjay-B commented
> > Code looks good. There's an empty `src/dashboard/dashboard.js` file that got pushed in. Not sure if that was intentional or by mistake. @aimiisme
> 
> The empty `src/dashboard/dashboard.js` file was pushed in intentionally as a "starting point" for frontend people to continue to work on that. The `Sign In` button on the `Login page` is linked to the `dashboard.js`. @Sanjay-B

That makes sense. I was just wondering incase it was a mistake. @aimiisme

2023-01-01 00:40 UTC, aimiisme commented on src/pages/login.js
> +                    {"Don't have an account? Sign Up"}
Agree, I will delete that.

2023-01-08 20:42 UTC, Sanjay-B approved these changes
LGTM. Thank you.

2023-01-08 20:42 UTC, merged