Convert all endpoints into a handler that calls an exported async function
KSU-Google-DSC/Webapp pull request #68
Opened 2023-01-01 21:59 UTC by johnnymcmike

This PR does as the title says, putting application logic (such as deleting an applicant, submitting a new one, or getting them all) for all endpoints into separate, exported async functions that frontend *should* be able to import and call directly. Very basic data validation has been added to the new submit function, ensuring that there will be no undefineds in the name key. api/applicants/[applicantKey]/index.js (the endpoint allowing one to get a particular applicant by its name key) has also been deleted to clear up clutter since we've never really had a use case for doing that, but let me know if we do still want that.

2023-01-02 17:58 UTC, Sanjay-B requested changes
You appear to have deleted the ``/api/applicants/[applicantKey]/index.js`` file. Is there a specific reason for this or was it done by mistake? @johnnymcmike

2023-01-02 17:58 UTC, Sanjay-B commented on src/pages/api/applicants/index.js
> +    return snapshot.docs.map(doc => doc.data());
What happens if this returns null? Does it return an empty table or does this error out? @johnnymcmike

2023-01-02 17:58 UTC, Sanjay-B commented on src/pages/api/applicants/submit.js
>  //This endpoint has been disabled for security reasons. As the code below stands, it would accept anyone's JSON and forward
You can remove all the commented out stuff. Keeping the codebase clean is important. @johnnymcmike

2023-01-02 18:01 UTC, Sanjay-B commented
I've included @teamrocket77 , @cgodwin0 & @IsaacAlao as part of this review since it's security related. @johnnymcmike

2023-01-02 18:06 UTC, johnnymcmike commented on src/pages/api/applicants/index.js
> +    return snapshot.docs.map(doc => doc.data());
Tested - returns an empty table, does not cause an error.

2023-01-02 18:10 UTC, johnnymcmike commented on src/pages/api/applicants/index.js
> +    return snapshot.docs.map(doc => doc.data());
> You appear to have deleted the `/api/applicants/[applicantKey]/index.js` file. Is there a specific reason for this or was it done by mistake? @johnnymcmike

It was done in the interest of code cleanliness, since I don't really think we're actually going to use it. Thought about it and it seems like there are only ever really going to be scenarios where you want to GET every applicant anyway, so why make 2 requests instead of just using the data you already got. But if there's something I haven't considered we can just put it back.

2023-01-02 18:11 UTC, johnnymcmike commented on src/pages/api/applicants/submit.js
>  //This endpoint has been disabled for security reasons. As the code below stands, it would accept anyone's JSON and forward
Done

2023-01-02 20:01 UTC, teamrocket77 commented on src/pages/api/applicants/submit.js
> +    if (data.firstName == undefined || data.lastName == undefined || data.email == undefined) {//TODO: move this validation to an adapter?
@johnnymcmike `""` can get through this, does our collection function seen below handle it properly? 

I guess as long as there is a key representing the input it doesn't matter

2023-01-02 23:00 UTC, teamrocket77 commented
Nice, @johnnymcmike thanks for that

2023-01-02 23:03 UTC, teamrocket77 approved these changes

2023-01-02 23:28 UTC, Sanjay-B requested changes
Functionality-wise, this looks good. Ideally, inputs need to be validated / sanitized better before this goes into production. React / Nextjs does this by default and our database is NoSQL which means that SQL injected attacks do not actually work. However, it's possible to attack a NoSQL database through cross-site scripting which the current code base doesn't support & needs to. @johnnymcmike cc: @teamrocket77

2023-01-02 23:28 UTC, Sanjay-B commented on src/pages/api/applicants/submit.js
> +    if (!(data.firstName && data.lastName && data.email)) {//TODO: move this validation to an adapter?
You could actually validate this input frontend (cc: @aimiisme ) or validate it here. Problem this poses is that if it's frontend only & frontend fails to validate certain things correctly, you create a vector of which someone could exploit. Which isn't all that helpful. However, if you validate only on the backend side, you risk pushing up malformed or exploitable text directly to your backend. For instance, ``"SELECT * FROM TABLE"``. Notice how this is a SQL statement inside a string. If I were to be really, really crafty, I could get past frontend (if it was validated as a string; technically this is correct since it's a string). With this implementation on backend, I could get past this too because, you're checking if any value exists for any one of those parameters. Which means, I have a direct line to infiltrate our database. 

Security is not just about detecting inputs. It's about filtering data in order to almost guarantee that the data being passed up is consider definitively correct. Extremely valuable skill to learn as a Software Engineer. Bad actors are everywhere. @johnnymcmike 

cc: @teamrocket77

2023-01-02 23:41 UTC, johnnymcmike commented on src/pages/api/applicants/submit.js
> +    if (data.firstName == undefined || data.lastName == undefined || data.email == undefined) {//TODO: move this validation to an adapter?
Good point, fixed. Shouldn't allow undefined or empty string now.

2023-01-02 23:44 UTC, Sanjay-B commented on src/pages/api/applicants/index.js
> +    return snapshot.docs.map(doc => doc.data());
There are scenarios where I would want to fetch only one applicant as opposed to all. For example, if I had 30 applicants, it wouldn't be beneficial if I fetched all 30 if I only really needed one. @johnnymcmike

2023-01-03 00:11 UTC, johnnymcmike commented on src/pages/api/applicants/submit.js
> +    if (!(data.firstName && data.lastName && data.email)) {//TODO: move this validation to an adapter?
1. If I understand what we're doing and what you've told me correctly, we kind of *are* validating this frontend, since this function is getting exported to be used in the frontend.
2. I understand what you're getting at. But other than testing to make sure the fields are strings, I don't know what more I could do to it to make it more secure. The three inputs are being used to make a string, which is being used as the name of a document in the database. I don't see where a XSS vector could be.

2023-01-03 01:04 UTC, Sanjay-B commented on src/pages/api/applicants/submit.js
> +    if (!(data.firstName && data.lastName && data.email)) {//TODO: move this validation to an adapter?
On the frontend, if an attacker enters ``"Hello "/><script>foo()</script>"`` as an input and it's passed to that function, your method does absolutely nothing to protect against that. As your code is written right now, it would simply be checked in as any of those values and then, it would be pushed upstream. Fun fact: Everything is actually considered backend because, Nextjs serves static pages that are rendered on the server. The biggest difference here is that inputs are binded at runtime to an action and that action is pushed to that method (not how it stands right now because, it's not connected). Biggest issue here is that there's no real way to distinguish ``"normal string"`` from ``<script> type="text/javascript"> // code </script>``. Which is a problem. Whatever data type your inputs require, should be only that & should not deviate. String enclosed as tags wouldn't count because, that's invalid. 

I do see what you're saying though that you should expect that all inputs to your method should be pre-sanitized before reaching. I'd agree but, I would never truly guarantee that to be the case at all times. It's better to not trust the client than to trust it. There's a saying or two out there that's relevant: "never trust the client" and "server-sided sanity checks". Both are really good practices. 

@johnnymcmike

2023-01-03 01:06 UTC, Sanjay-B requested changes

2023-01-03 01:06 UTC, Sanjay-B commented on src/pages/api/applicants/[applicantKey]/index.js
> +export default async function handler(req, res) {
Handler is not needed since the applicant's submission will always remain private. @johnnymcmike

2023-01-08 20:35 UTC, Sanjay-B approved these changes
LGTM. Thank you.

2023-01-08 20:35 UTC, Sanjay-B commented on src/pages/api/applicants/[applicantKey]/index.js
> +    else {
nitpick: This ``else statement`` isn't needed.

2023-01-08 20:36 UTC, merged