Add more endpoints and basic auth implementation
KSU-Google-DSC/Webapp pull request #88
Opened 2023-01-31 04:42 UTC by johnnymcmike

This PR adds a handful of API endpoints:
-api/events/all
-api/events/add
-api/auth/login
-api/auth/logout
-api/applicants/count
-api/applicants/count/bymonth
-api/applicants/[applicantKey]
-api/applicants/[applicantKey]/delete

And an entirely reworked, functioning auth implementation based on Firebase Auth and this [next-firebase-auth](https://github.com/gladly-team/next-firebase-auth) package, rather than the old strategy of trying to leverage nextauth using firebase as a DB.

Notes for reviewers:
-Currently there is nothing role-based in this implementation, all of the new & old endpoints (save for api/events/all, since this is meant to be public) have a check to see if the user is signed in and return a 401 if they are not, letting them through otherwise. This is currently done with a copy-pasted if block, which will later be replaced by a function that instead checks if their account has the right roles to do that thing. TL;DR: Everyone who makes an account is basically an admin, don't merge this into main yet.

-Login page is going to have to tweak its implementation somewhat to work with this new package. logintest.js and authtest.js have been added as example sign-in and "are you signed in" pages, to be removed when appropriate. Currently logging out can only be done by navigating to /api/auth/logout.

2023-01-31 05:07 UTC, Sanjay-B requested changes
Impressive stuff. Requested changes / clarification.

2023-01-31 05:07 UTC, Sanjay-B commented on src/pages/api/applicants/count/bymonth.js
> +import { getUserFromCookies } from 'next-firebase-auth';
What is the purpose of this endpoint?

2023-01-31 05:07 UTC, Sanjay-B commented on src/pages/api/applicants/count/index.js
> +//endpoint that returns the number of applicant documents in the applicants collection of the database
Could you not you just get the length of getall in a previous endpoint? Is this different?

2023-01-31 05:07 UTC, Sanjay-B commented on src/pages/api/applicants/index.js
> +  console.log(await getUserFromCookies({ req: req }));
Nitpick: We don't need this to clutter our logs in prod.

2023-01-31 05:07 UTC, Sanjay-B commented on src/pages/api/applicants/submit.js
> +export default async function handler(req, res) {
Don't need a handler. It's only for GET requests.

2023-01-31 05:07 UTC, Sanjay-B commented on src/pages/api/auth/login.js
> +const handler = async (req, res) => {
Is this a login or really, just a refresh?

2023-01-31 05:07 UTC, Sanjay-B commented on src/pages/api/events/add.js
> +export default async function handler(req, res) {
Don't need handler. Only GET requests.

2023-01-31 05:07 UTC, Sanjay-B commented on src/pages/authtest.js
> +import React from 'react'
You should make this an actual unit test. Because, if this goes in prod, it'll act as an actual page.

2023-01-31 05:07 UTC, Sanjay-B commented on src/pages/logintest.js
> +//example component from
You should make this a Unit Test & not a page.

2023-01-31 05:12 UTC, johnnymcmike commented on src/pages/api/applicants/count/bymonth.js
> +import { getUserFromCookies } from 'next-firebase-auth';
Metric dashboard screenshots that Aimi showed me had a histogram with new applications per-month. This is supposed to accommodate for that.

2023-01-31 05:12 UTC, johnnymcmike commented on src/pages/api/applicants/index.js
> +  console.log(await getUserFromCookies({ req: req }));
Thought I already removed this. Done

2023-01-31 05:35 UTC, johnnymcmike commented on src/pages/authtest.js
> +import React from 'react'
It's intentionally acting as an actual page right now, not intended for prod, meant to be removed whenever we don't need it. I copied it from their example app just for the sake of ease of testing functionality. I don't know how to write actual unit tests, but I remember you saying something about Automation putting out some kind of guide, so I'll look over that.

2023-01-31 05:45 UTC, johnnymcmike commented on src/pages/api/auth/login.js
> +const handler = async (req, res) => {
Not sure. It was in their example app, and it seems to be required in some way because the path to this endpoint is a required paramater for initializing next-firebase-auth. The actual login functionality does seem to be at least partially elsewhere, look at the new component that logintest.js uses if you want to know more

2023-01-31 05:49 UTC, Sanjay-B commented on src/pages/api/auth/login.js
> +const handler = async (req, res) => {
Interesting. Thanks for the clarification.

2023-01-31 05:49 UTC, Sanjay-B commented on src/pages/authtest.js
> +import React from 'react'
Follow up with Vincent & Isaac about it. They should know. Resolving this.

2023-01-31 06:16 UTC, johnnymcmike commented on src/pages/api/applicants/count/index.js
> +//endpoint that returns the number of applicant documents in the applicants collection of the database
Yeah, but where would I be returning that? I can just delete this file if it isn't really useful to us to have a total count of all applications ever as an endpoint. Or alternatively just move that count function to the file the get all endpoint is in

2023-01-31 06:24 UTC, Sanjay-B commented on src/pages/api/applicants/count/index.js
> +//endpoint that returns the number of applicant documents in the applicants collection of the database
You could make a separate method and just, get the length of the return. In this case, ``getAll().keys()``.

2023-01-31 06:25 UTC, Sanjay-B commented on src/pages/api/applicants/count/bymonth.js
> +import { getUserFromCookies } from 'next-firebase-auth';
Oh, so this is filtering. I'd make a search method that allows you to filter stuff out instead of this. i.e limit, cursor, sortOrder, etc.

2023-01-31 06:27 UTC, johnnymcmike commented on src/package.json
> +    "fs": "^0.0.1-security",
No idea, went through a period of thinking some bugs were package-based (fs in particular only works on server side and i was trying to call it indirectly on client) and typed `npm i fs`. Don't have an explanation for the blank entry. Changing this stuff shouldn't break what I have working.

2023-01-31 21:57 UTC, teamrocket77 requested changes

2023-01-31 21:57 UTC, teamrocket77 commented on src/package.json
> +    "fs": "^0.0.1-security",
I was having some issues with the `fs` (supposedly not installed) modules when troubleshooting the env issue. I think it is installed by default, not sure tho

2023-01-31 21:57 UTC, teamrocket77 commented on src/pages/api/applicants/count/bymonth.js
> +import { getUserFromCookies } from 'next-firebase-auth';
^^ Agreed, dynamic is the way should do nicely for any changes we or anyone else may want to make., Maybe this should be just an outline since there could be lots of functionality implied here. && it's already a large PR

2023-01-31 21:57 UTC, teamrocket77 commented on src/pages/logintest.js
> +//example component from
Can someone explain what's happening in this file? 
If it's a unit test we have them in the `src/cypress/e2e/*` folder, you can make a `backend` folder and prefix it with `backend.<something>.cy.js. There are examples in the front end folder.
We will get started writing something that runs the back end tests.
If you want a brief overview of cypress 
check [this out](https://github.com/KSU-Google-DSC/Webapp/blob/main/docs/automation/CYPRESS_README.md) 
Ping me with any issues, you don't have to write it by yourself, all for doing it together if you're down. However, I will have to have an understanding of what's happening here to write it

2023-01-31 22:19 UTC, johnnymcmike commented on src/pages/logintest.js
> +//example component from
It's not a unit test, it's a temporary login page that's not supposed to make it into prod, just for making sure auth actually works without having to rework the existing real login page myself. I copied it from the library's [example project here](https://github.com/gladly-team/next-firebase-auth/tree/v1.x/example). Sorry if the "test" name threw you off.

2023-01-31 22:37 UTC, johnnymcmike commented on src/package.json
> +    "fs": "^0.0.1-security",
So in my research the "fs isn't installed" stuff apparently happens when you're trying to run code from a library meant for node.js in the browser. Since fs is the filestystem-accessing library and all. It turned out that my issue was with code and didn't have anything to do with fs not being installed or any packages being the wrong version.

2023-02-06 06:00 UTC, teamrocket77 commented on src/initAuth.js
> +    firebaseAdminInitConfig: {
@johnnymcmike I don't know what the current state it but you might be able to use an optional. As seen [here](https://github.com/KSU-Google-DSC/Google-Summit-Solution/blob/api/signup/src/pages/signup.js)

2023-02-06 06:18 UTC, teamrocket77 requested changes

2023-02-06 06:18 UTC, teamrocket77 commented on src/database.js
> +}) : getApp();
Why was the `COMMON` string removed?

2023-02-06 06:18 UTC, teamrocket77 commented on src/pages/logintest.js
> +//example component from
@johnnymcmike if it shouldn't make it into prod why do we have it?

2023-02-06 06:18 UTC, teamrocket77 commented on src/pages/api/applicants/submit.js
> +  if (!(data.firstName && data.lastName && data.email)) {//TODO: move this validation to an adapter?
I see that you have a question here. Isn't it possible to do on the frontend? Wouldn't backend processing and validation be slow. [Validation from Moz](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#using_built-in_form_validation)

2023-02-06 06:18 UTC, teamrocket77 commented on src/pages/api/applicants/submit.js
> +  if ((data.firstName + data.lastName + data.email).contains('<script')) {//one more XSS check to be safe
Nothing wrong with additional protection but in our `next.config.js` I think we filter for this already

2023-02-06 06:18 UTC, teamrocket77 commented on src/package.json
> +    "fs": "^0.0.1-security",
@johnnymcmike so it'll be removed?

2023-02-06 06:43 UTC, johnnymcmike commented on src/database.js
> +}) : getApp();
this was through trial and error - the library initializes a default firebase app, this code (on which we used to rely for initialization) initialized a firebase app with the name "COMMON", which was separate from the one the library was making. the goal was to have the library just init firebase-admin at the start and then be able to get it anywhere with firebase.getApp(). I remember this working for a time, but then I ended up having to bring back the whole code block in database.js because things would only get initialized if you visited an auth page, and it would give you an error if you started up the app and then visited a db page first.

TLDR: i'm not sure, but it works right now. if we need it to be named "COMMON" for some other reason, then even with that string restored it will probably break if a login page is visited before a database page.

2023-02-06 06:46 UTC, johnnymcmike commented on src/pages/api/applicants/submit.js
> +  if ((data.firstName + data.lastName + data.email).contains('<script')) {//one more XSS check to be safe
that's what sanjay said but it was suggested to add it anyway

2023-02-08 01:46 UTC, closed without merging