Code coverage implementation
KSU-Google-DSC/Webapp pull request #89
Opened 2023-01-31 07:37 UTC by IsaacAlao

### This PR will generate a code coverage report [#70] 

The following will be generated/altered:
 - commit status (will display code-coverage percentage).
 - code coverage badge (located in ``./src/README.md`` and will update accordingly after the action runs successfully). 
   - e.g. :
   ![](https://img.shields.io/badge/code--coverage-100%25-brightgreen)

 
Why is this needed?:
- To quantify various code being tested
- To identify any potential issues

Misc:
- If you wish to run coverage reports locally:
```bash
# Assuming you are in src and already have the necessary packages installed:

# This script will run the webserver and run cypress tests on localhost:3000
# and will yield coverage and .nyc_report folders/directories
npm run e2e:headless

# This script will generate a text based summary of the statement(s) evaluated, etc.
npm run coverage

# You can access the HTML report by going to: coverage → lcov-report → index.html
```

2023-01-31 08:02 UTC, IsaacAlao commented
Before approving this PR please note that in the ``integration.yml`` file, the ``BRANCH_NAME`` needs to be changed to 'dev'.

Thank you.

2023-01-31 17:28 UTC, teamrocket77 commented
Fix linting issues, in general

2023-01-31 17:28 UTC, teamrocket77 commented
Also fix the dependency issues

2023-01-31 17:32 UTC, teamrocket77 requested changes
Address changes for favor

2023-01-31 17:32 UTC, teamrocket77 commented on .github/workflows/integration.yml
> +        #uses: cypress-io/github-action@v5
Why's all of this commented out if we don't need it remove it

2023-01-31 17:32 UTC, teamrocket77 commented on src/cypress.config.js
> +//       // implement node event listeners here
Same point here we don't need commented out code

2023-01-31 17:32 UTC, teamrocket77 commented on src/cypress.config.js
> -  video : false,
We need this to be false, this really Impacts GitHub action time. We can revisit this at a later date with more options if we need

2023-01-31 17:32 UTC, teamrocket77 commented on src/cypress/integration/example.spec.js
> +// Example Test.
What's the purpose of this test?
Are we able to get it running without this?

2023-01-31 17:32 UTC, teamrocket77 commented on src/cypress/support/commands.js
> +// This example commands.js shows you how to
Why do we have this file

2023-01-31 17:33 UTC, teamrocket77 commented
Integration test run but they break, because you have an error. Why doesn't container build now? 
Check out the GitHub Action logs

2023-01-31 18:56 UTC, IsaacAlao reviewed
Fixed.

2023-01-31 20:40 UTC, IsaacAlao commented on .github/workflows/integration.yml
> +        #uses: cypress-io/github-action@v5
Sorry about that!

2023-01-31 22:58 UTC, Sanjay-B requested changes
LGTM. Clarify some stuff.

2023-01-31 22:58 UTC, Sanjay-B commented on src/package.json
> +    "coverage": "nyc report --reporter=text-summary",
Rename this to ``code_coverage``. ``coverage`` is too ambiguous.

2023-01-31 22:58 UTC, Sanjay-B commented on src/package.json
> +    "start-server-and-test": "^1.15.3",
What is this?

2023-02-01 03:42 UTC, IsaacAlao commented on src/package.json
> +    "start-server-and-test": "^1.15.3",
cypress: what we use to run e2e (end-to-end) tests or component tests
@cypress/code-coverage: saves code coverage reports
check-code-coverage: tools for displaying and presenting code coverage reports
start-server-and-test: starts the webserver and runs the test command

2023-02-02 00:11 UTC, Sanjay-B approved these changes
LGTM.

2023-02-02 00:45 UTC, Sanjay-B commented on src/package.json
> +    "start-server-and-test": "^1.15.3",
Alright, thanks for clarifying.

2023-02-05 05:58 UTC, teamrocket77 commented
@IsaacAlao last I checked this PR was not working has anything changed? Will mark as requested changes unless answer is yes lol

2023-02-05 05:59 UTC, teamrocket77 commented on .github/workflows/integration.yml
> +        uses: actions/checkout@v3
this should be pinned via sha as seen in other [actions](https://github.com/KSU-Google-DSC/Webapp/blob/dev/.github/workflows/integration.yml)

2023-02-05 06:01 UTC, teamrocket77 requested changes
See [me](https://github.com/KSU-Google-DSC/Webapp/pull/89#issuecomment-1416930091)

2023-02-05 07:56 UTC, IsaacAlao reviewed
Changed.

2023-02-05 08:00 UTC, IsaacAlao commented
@teamrocket77 The only problem with the PR is the docker build job (which I didn't modify and it fails because of some webpack error). I'll investigate the issue sometime later.

2023-02-05 08:16 UTC, IsaacAlao commented on .github/workflows/integration.yml
> +        uses: actions/checkout@v3
Will work on that.

2023-02-06 19:35 UTC, IsaacAlao reviewed
👍

2023-02-08 05:36 UTC, teamrocket77 requested changes

2023-02-08 05:36 UTC, teamrocket77 commented on src/cypress/support/index.js
> +import '@cypress/code-coverage/support'
I know it seemed reasonable, but why are is this present in this file and the e2e.js file? I know that the process was troubleshooting trying to get it working, but are we able to run the code coverage job without it?

2023-02-08 05:36 UTC, teamrocket77 commented on src/cypress.config.js
> +      require("@cypress/code-coverage/task")(on, config);
In one of the previous commits this pointed to a support file, do we need this line? Do we need the support files?

2023-02-08 05:36 UTC, teamrocket77 commented on src/package.json
> +    "@babel/core": "^7.20.12",
Looking back we might be able to get rid of all of these babel plugins, I added them in haste looking to solve the cannot find module issue, if we don't need it let's trim it. I will build locally and see. Check back for more info

2023-02-08 06:03 UTC, teamrocket77 commented on src/package.json
> +    "@babel/core": "^7.20.12",
It builds locally with without the required files. 
[docker.log](https://github.com/KSU-Google-DSC/Webapp/files/10682257/docker.log)
In addition to that, we are still able to run the code: coverage process, could you try removing these and pushing?

2023-02-11 03:17 UTC, IsaacAlao commented on src/cypress.config.js
> +      require("@cypress/code-coverage/task")(on, config);
That line is needed. Support files can be used before spec files get loaded, but I'm not sure we have a use for them now, at the moment.

2023-02-11 03:23 UTC, IsaacAlao commented on src/cypress/support/index.js
> +import '@cypress/code-coverage/support'
There's really no use for both files right at this time, but it is convenient to have them there if we plan to use them in the near future.

2023-02-11 19:23 UTC, teamrocket77 commented on src/cypress/support/index.js
> +import '@cypress/code-coverage/support'
@IsaacAlao, Lets remove the things that we don't need right now

2023-02-12 00:32 UTC, IsaacAlao commented on src/cypress/support/index.js
> +import '@cypress/code-coverage/support'
And the support directory alongside the files within it are needed to generate the `coverage` and `.nyc_output` directories: 
(scroll down to **E2E code coverage**)
https://docs.cypress.io/guides/tooling/code-coverage

2023-02-12 00:35 UTC, IsaacAlao commented on src/cypress.config.js
> +      require("@cypress/code-coverage/task")(on, config);
Actually that line is not needed since it prevents cypress from generating `coverage` and `.nyc_output` in `src`.

2023-02-12 15:40 UTC, teamrocket77 approved these changes

2023-02-12 15:43 UTC, merged